### ISSUE TITLE
Lesser Bitumen

### ISSUE THREAD

**Issue by MegaGamer265** [KillerMapper/roadstuff#25]
There is just way to much bitumen, its annoying. Isnt there a way to reduce the spawn rate?

**Comment by MapperTV** [comment]
You can change the spawn rate in the config file (located in the config folder, named mapperbase-common.toml). You can change pocket sizes, chances for them to generate and blacklist / whitelist biomes where they will be present. If you don't use it you can disable the generation as well.

I admit I am not satisfied with how bitumen generates too, I tried to make them big and less frequent but couldn't find a good balance. Since it is used to build roads with Road Stuff (another of my mods) large quantities are needed. I'll probably change things in the future.
