### ISSUE TITLE
Issue: Problems with Carpenter's Blocks

### ISSUE THREAD

**Issue by Skkubah** [KillerMapper/roadstuff#9]
Greetings,

While attempting to make a nice slope on a road, I've decided to use the Carpenter's Wedge Slopes and the Carpenter's Collapsible Blocks, but there is a problem: whatever direction I apply the block to the Slopes/Collapsible Blocks, they always are like I've placed them heading the North direction. The versions are: Road Stuff v1.0.2-final; Carpenter's Blocks v3.3.8.1 - (MC v1.7.10; MCF v10.13.4.1614)

![2017-01-19_22 39 29](https://cloud.githubusercontent.com/assets/10351506/22131395/41f3858e-de9a-11e6-90b4-8bb2970173c9.png)

![2017-01-19_22 42 45](https://cloud.githubusercontent.com/assets/10351506/22131398/465831ce-de9a-11e6-831c-a7447faabb68.png)

Thank you for your time.

**Comment by KillerMapper** [comment]
Hello,

Unfortunately, this is a problem that can't be solved on my side. Since I use some rendering methods to rotate the texture and save memory, Carpenters seems to not take this in account so the display is wrong.

Either I put rotated variants of the textures, which makes no sense for me (and I stopped the 1.7.10 support by now) or Carpenters' Blocks would have to add something to detect texture rotation (I don't know if it is possible, and if 1.7.10 is still supported here as well).

**Comment by Skkubah** [comment]
Thank you for replying, I will try to bring this up to the developers of Carpenter's Blocks, see if is there anything they can do about this.

**Comment by Skkubah** [comment]
Just for the purpose of documentation, here is the topic about this problem with the developer of the Carpenter's Blocks: [https://github.com/Mineshopper/carpentersblocks/issues/382](url)
